import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CLI = join(HERE, '..', 'packages', 'proxy', 'src', 'cli.js');
const PACKAGE_JSON = join(HERE, '..', 'packages', 'proxy', 'package.json');
const STAGED_WORKFLOW = join(HERE, '..', '..', '.github', 'workflows', 'npm-staged-publish.yml');

function isolatedEnv(root) {
  return {
    ...process.env,
    HOME: root,
    SHELL: '/bin/zsh',
    CODEX_HOME: join(root, '.codex'),
    CLAUDE_HOME: join(root, '.claude'),
    CURSOR_HOME: join(root, '.cursor'),
    GROK_HOME: join(root, '.grok'),
    HERMES_HOME: join(root, '.hermes'),
    TOKIMETER_DATA_DIR: join(root, '.tokimeter'),
    TOKIMETER_PRICING_FILE: join(root, '.tokimeter', 'pricing.json'),
    TOKIMETER_PRICING_FEED_FILE: join(root, '.tokimeter', 'pricing-feed.json'),
    TOKIMETER_PTY: '0',
  };
}

function tree(root) {
  const result = [];
  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      result.push(path.slice(root.length + 1));
      if (entry.isDirectory()) walk(path);
    }
  };
  walk(root);
  return result.sort();
}

test('setup --dry-run prints exact plan and performs no mutation', (t) => {
  const root = mkdtempSync(join(tmpdir(), 'tokimeter-setup-dry-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const before = tree(root);
  const output = execFileSync(process.execPath, [CLI, 'setup', '--auto', '--dry-run'], {
    encoding: 'utf8',
    env: isolatedEnv(root),
  });

  assert.match(output, /Tokimeter Setup Dry Run/);
  assert.match(output, new RegExp(join(root, '.codex', 'tokimeter.config.toml').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(output, new RegExp(join(root, '.claude', 'settings.json').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(output, new RegExp(join(root, '.tokimeter', 'bin', 'codex').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(output, /No files, processes, or settings were changed/);
  assert.match(output, /tokimeter uninstall/);
  assert.deepEqual(tree(root), before);
});

test('setup plan is shown before mutation and uninstall restores prior configs', (t) => {
  const root = mkdtempSync(join(tmpdir(), 'tokimeter-setup-restore-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const env = isolatedEnv(root);
  mkdirSync(env.CODEX_HOME, { recursive: true });
  mkdirSync(env.CLAUDE_HOME, { recursive: true });

  const apiProfile = join(env.CODEX_HOME, 'tokimeter.config.toml');
  const chatgptProfile = join(env.CODEX_HOME, 'tokimeter-chatgpt.config.toml');
  const claudeSettings = join(env.CLAUDE_HOME, 'settings.json');
  const priorApi = '# user-owned synthetic profile\nmodel = "example"\n';
  const priorChatgpt = '# user-owned synthetic subscription profile\n';
  const priorClaude = {
    statusLine: { type: 'command', command: 'synthetic-status-command' },
    spinnerVerbs: { mode: 'append', verbs: ['Synthetic'] },
    unrelated: true,
  };
  writeFileSync(apiProfile, priorApi);
  writeFileSync(chatgptProfile, priorChatgpt);
  writeFileSync(claudeSettings, `${JSON.stringify(priorClaude, null, 2)}\n`);

  const setupOutput = execFileSync(process.execPath, [CLI, 'setup'], { encoding: 'utf8', env });
  assert.ok(setupOutput.indexOf('Tokimeter Setup Plan') < setupOutput.indexOf('Codex API-key profile written'));
  assert.match(setupOutput, /Revert setup changes with: tokimeter uninstall/);
  assert.match(readFileSync(apiProfile, 'utf8'), /Generated by Tokimeter/);
  assert.match(JSON.parse(readFileSync(claudeSettings, 'utf8')).statusLine.command, /claude-statusline\.mjs/);

  const uninstallOutput = execFileSync(process.execPath, [CLI, 'uninstall'], { encoding: 'utf8', env });
  assert.match(uninstallOutput, /Restored prior Codex profiles/);
  assert.match(uninstallOutput, /Restored Claude status line/);
  assert.equal(readFileSync(apiProfile, 'utf8'), priorApi);
  assert.equal(readFileSync(chatgptProfile, 'utf8'), priorChatgpt);
  assert.deepEqual(JSON.parse(readFileSync(claudeSettings, 'utf8')), priorClaude);
  assert.equal(existsSync(join(env.TOKIMETER_DATA_DIR, 'codex-profiles-prev.json')), false);
  assert.equal(existsSync(join(env.TOKIMETER_DATA_DIR, 'claude-statusline.mjs')), false);
  assert.equal(existsSync(join(env.TOKIMETER_DATA_DIR, 'claude-statusline-prev.json')), false);
});

test('npm package has no install hooks and release workflow is stage-only', () => {
  const pkg = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8'));
  assert.equal(Object.hasOwn(pkg.scripts || {}, 'install'), false);
  assert.equal(Object.hasOwn(pkg.scripts || {}, 'postinstall'), false);

  const workflow = readFileSync(STAGED_WORKFLOW, 'utf8');
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /id-token: write/);
  assert.match(workflow, /npm stage publish/);
  assert.doesNotMatch(workflow, /\bnpm publish\b/);
});
